apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "cmFuNzg5MTpkY2tyX3BhdF9LRm9OUFFtNDY4TlhPQURlNTZ4aUJPZTNLVmM="
        }
      }
    }
