apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wallet-msgtransfer
spec:
  serviceName: "wallet-msgtransfer-service"
  replicas: 1
  selector:
    matchLabels:
      app: wallet-msgtransfer
  template:
    metadata:
      labels:
        app: wallet-msgtransfer
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: wallet-msgtransfer
          image: akachat/server
          imagePullPolicy: Always
          env:
            - name: CONFIG_PATH
              value: /config
            - name: WALLETENV_MYSQLDB_URI
              valueFrom:
                secretKeyRef:
                  name:  mysql-secret
                  key: mysql_openim_uri
            - name: WALLETENV_MYSQLDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name:  mysql-secret
                  key: mysql_openim_username
            - name: WALLETENV_MYSQLDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_openim_password
            - name: WALLETENV_KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openim-kafka-secret
                  key: kafka-username
            - name: WALLETENV_KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openim-kafka-secret
                  key: kafka-password

          volumeMounts:
            - name: im-wallet-config
              mountPath: /config
              readOnly: true
            - name: general-cert
              mountPath: /certs/amazon-ca.pem
              subPath: amazon-ca.pem
              readOnly: true
          ports:
            - containerPort: 19020
            - containerPort: 7000
          livenessProbe:
            exec:
              command:
                - pgrep
                - aka-wallet-msgtransfer
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - pgrep
                - aka-wallet-msgtransfer
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: im-wallet-config
          configMap:
            name: wallet-config
        - name: general-cert
          secret:
            secretName: general-cert
