apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: im-msggateway
      namespace: default # 关键：和 overlay 的 namespace 一致
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          alibabacloud.com/nodepool-id: npa34ac756a1b042f2ad17d64918562096
images:
  - name: akachat/server
    newTag: 0264d656a5eb24c61d35a87ae788b16a-4872c49
    newName: ran7891/aka-im-msggateway
